--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.341.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27/02/2024 21:05:28
-- Server version: 5.5.5-10.4.28-MariaDB
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE test;

--
-- Definition for table estoque
--
DROP TABLE IF EXISTS estoque;
CREATE TABLE estoque (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(25) DEFAULT 'NULL',
  valvenda DOUBLE DEFAULT NULL,
  grupo VARCHAR(25) DEFAULT 'NULL',
  corgrupo VARCHAR(25) DEFAULT 'NULL',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 12
AVG_ROW_LENGTH = 2340
CHARACTER SET latin1
COLLATE latin1_swedish_ci
ROW_FORMAT = DYNAMIC;

-- 
-- Dumping data for table estoque
--
INSERT INTO estoque VALUES
(5, 'Fanta Laranja', 8.9, 'Bebidas', NULL),
(6, 'Fritas 500g', 29.9, 'Porções', NULL),
(7, 'Polenta Frita 500g', 21.9, 'Porções', NULL),
(8, 'Rodízio Pizza', 89.9, 'Rodízio', NULL),
(9, 'Rodízio Promocional', 65.5, 'Rodízio', NULL),
(10, 'Energético red Pill', 10, 'Bebidas', NULL),
(11, 'Pastel de Queijo', 8.8, 'Lanches', NULL);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;